// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: tokens.sql

package repo

import (
	"context"
)

const craeateTokens = `-- name: CraeateTokens :one
INSERT INTO tokens (jwt_token, refresh_token) 
VALUES ($1, $2)
RETURNING id, jwt_token, refresh_token
`

type CraeateTokensParams struct {
	JwtToken     string
	RefreshToken string
}

func (q *Queries) CraeateTokens(ctx context.Context, arg CraeateTokensParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, craeateTokens, arg.JwtToken, arg.RefreshToken)
	var i Token
	err := row.Scan(&i.ID, &i.JwtToken, &i.RefreshToken)
	return i, err
}
