// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: users.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, full_name, email, nick_name, age, password_hash) 
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, full_name, email, nick_name, age, password_hash
`

type CreateUserParams struct {
	ID           uuid.UUID
	FullName     string
	Email        string
	NickName     string
	Age          int16
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.NickName,
		arg.Age,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.NickName,
		&i.Age,
		&i.PasswordHash,
	)
	return i, err
}
